### ISSUE TITLE
Add support allowing sign-ins with Google accounts

### ISSUE THREAD

**Issue by commonplace** [aaroneiche/do-want#109]
There's plenty I'd still love to see added, but this is probably number one -- if users could sign in using a Google (or Facebook or Amazon or Twitter, but really, Google is number one) account rather than making an account just for my wishlist... that'd be huge.

**Comment by aaroneiche** [comment]
This requires some pretty significant overhaul, but I am looking into an interim solution that could be deployed with minimal changes.

**Comment by aaroneiche** [comment]
So to clarify @commonplace, Are you looking for account creation and login with Google, or just for attaching Google accounts to existing Do Want accounts so you can long in with google instead?

**Comment by commonplace** [comment]
Yes to both, but I'll take what I can get!

**Comment by aaroneiche** [comment]
I've got login working. It requires an additional table. The hard stuff is making it easy for users to create a new account with it, or add a social login to their account, without breaking something.

Also, getting the UI to work everywhere. Anyway, progress is progressing.

**Comment by commonplace** [comment]
I like the progress!!!! Thank you so much!!

**Comment by commonplace** [comment]
I actually decided to switch to Amazon for our wishlists, but I have
changed my mind because Do-Want has several things Amazon doesn't. The
biggest (to me) is the ability to reserve items without actually buying
them immediately. I found several other shortcomings with Amazon's wishlist
system, too.

So my mother-in-law who just can't remember her Do-Want password EVER will
be able to logon using another account (Google, Facebook, whatever -- she
manages to remember those, *usually*) and get with the program.

Super excited!

**Comment by aaroneiche** [comment]
Unless she logs out of one of those services explicitly, she should be able to simply click the button and be logged in. You can also associate an account with multiple systems, so as long as she can remember the login for one of them, she should be okay. But if she remains logged into facebook or google, it really shouldn't be an issue. Just a button push (and that I hope to fix soon as well with a proper login cookie)

**Comment by commonplace** [comment]
Even better!! :)

**Comment by aaroneiche** [comment]
This has been implemented, working towards a release so people can actually use this. (commit 7f3bd080+)
