### ISSUE TITLE
Tool icon alignment

### ISSUE THREAD

**Issue by jduino** [aaroneiche/do-want#94]
Minor/cosmetic issue. Tool icons do not stay lined up in a particular 'column' when different numbers of icons are present. Attached is a photo from Firefox 25 on Linux (FC19). Same thing under Chrome. This is when viewing another's list.
![tool_icon_alignment](https://f.cloud.github.com/assets/6015927/1635632/424b6158-57b3-11e3-8a96-4853e970c275.png)

**Comment by aaroneiche** [comment]
I don't believe this issue exists anymore since all the icons were updated to the same size. Closing unless we encounter it again.
